services:
  dind: # Docker-in-Docker (DinD) service
    image: docker:dind
    container_name: dind
    privileged: true # privileged mode required for Docker-in-Docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes: # Named volumes for Jenkins data and Docker certs
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: unless-stopped
    user: root
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

volumes:
  jenkins-data:
  docker-certs-ca:
  docker-certs-client:

networks:
  jenkins:
    driver: bridge